name: Marlin PlatformIO CI

on: 
  push:
    branches: [ ender3-pro ]
  pull_request:
    branches: [ ender3-pro ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
    - name: Run PlatformIO
      run: platformio run -e sanguino1284p
    - name: Upload builded firmware
      uses: actions/upload-artifact@v1
      with:
        name: ender3-mesh-bl-5x5.hex
        path: .pio/build/sanguino1284p/firmware.hex
